name: build symengine
on:
  push:
    branches:
      - symengine-win22

jobs:

  windows:
    name: build symengine (windows)
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: ['Release', 'Debug']
        shared: ['True', 'False']
    env:
      CONAN_REVISIONS_ENABLED: 1
    steps:
    - uses: actions/checkout@v2
    - name: install conan
      run: pip install conan
    - name: create profile
      run: conan profile new tket --detect
    - name: normalize line endings in conanfile
      run: |
        $conanfile ='recipes/symengine/conanfile.py'
        $normalized_file = [IO.File]::ReadAllText($conanfile) -replace "`r`n", "`n"
        [IO.File]::WriteAllText($conanfile, $normalized_file)
    - name: build symengine
      run: conan create --profile=tket -s build_type=${{ matrix.build_type }} -o symengine:shared=${{ matrix.shared }} recipes/symengine tket/stable
    - name: add remote
      run: conan remote add tket-conan https://tket.jfrog.io/artifactory/api/conan/tket-conan
    - name: authenticate to repository
      run: conan user -p ${{ secrets.JFROG_ARTIFACTORY_TOKEN_1 }} -r tket-conan ${{ secrets.JFROG_ARTIFACTORY_USER_1 }}
    - name: get version
      run: |
        $symengine_ver = conan inspect --raw version recipes/symengine/
        echo "SYMENGINE_VER=${symengine_ver}" >> $env:GITHUB_ENV
    - name: upload package
      run: conan upload symengine/${{ env.SYMENGINE_VER }}@tket/stable --all -r=tket-conan
