name: nightly test-coverage

on:
  schedule:
    # 03:00 every Saturday morning
    - cron: '0 4 * * 6'

jobs:

  linux:
    name: Execute coverage test (Linux)
    runs-on: ubuntu-20.04
    env:
      PYTKET_SKIP_REGISTRATION: "true"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Get current time
      uses: srfrnk/current-time@v1.1.0
      id: current_time
      with:
        format: YYYYMMDDHHmmss
    - name: Cache ccache data
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-tket-ccache-${{ steps.current_time.outputs.formattedTime }}
        restore-keys: |
          ${{ runner.os }}-tket-ccache-
    - name: Install conan
      id: conan
      # urllib3 because of TKET-865 (remove when conan fixes its dependencies)
      # install gcovr package for coverage test
      # conan profile: change to debug mode
      run: |
        pip install urllib3==1.25.11 conan
        conan_cmd=/home/runner/.local/bin/conan
        ${conan_cmd} profile new tket --detect
        ${conan_cmd} profile update settings.compiler.libcxx=libstdc++11 tket
        ${conan_cmd} profile update settings.build_type=Debug tket
        echo "CONAN_CMD=${conan_cmd}" >> $GITHUB_ENV
        pip install gcovr
    - name: Install ninja and ccache
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build ccache gcovr
    - name: Build tket
      run: ${CONAN_CMD} create --profile=tket recipes/tket
    - name: Install runtime test requirements
      run: |
        sudo apt-get install texlive texlive-latex-extra latexmk
        mkdir -p ~/texmf/tex/latex
        wget http://mirrors.ctan.org/graphics/pgf/contrib/quantikz/tikzlibraryquantikz.code.tex -P ~/texmf/tex/latex
    - name: Install gcovr
      run: pip install gcovr
    - name: Build tket-coverage
      run: ${CONAN_CMD} create --profile=tket recipes/tket-coverage
    # TODO Deploy somewhere public.
    # E.g. https://github.com/peaceiris/actions-gh-pages
    # - name: Login via Azure CLI
    #   uses: azure/login@v1
    #   with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}
    # - name: find directory for html files
    #   run: |
    #     cd /home/runner/.conan/data/tket-coverage
    #     cd *
    #     cd _/_/build
    #     cd *
    #     cd coverage
    #     coverage_html=$(pwd)
    #     echo "COVERAGE_HTML=${coverage_html}/" >> $GITHUB_ENV
    #     echo $COVERAGE_HTML
    # - uses: azure/webapps-deploy@v2
    #   with:
    #    app-name: 'BubbleCoverage'
    #    package: ${{ env.COVERAGE_HTML }}
