name: Release

on:
  push:
    branches:
      - test-manylinux-setuptools-scm

jobs:
  build_Linux_wheels:
    name: Build manylinux
    runs-on: ubuntu-20.04
    env:
      PY_VERS: cp38-cp38
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up container
      run: |
        docker create --name linux_build -i -v /:/host quay.io/pypa/manylinux2014_x86_64:latest /bin/bash
        docker cp . linux_build:/tket/
    - name: Run build
      run: |
        docker start linux_build
        docker exec -e PY_VERS="${PY_VERS}" linux_build /bin/bash -c "/tket/.github/workflows/linuxbuildwheel"
        mkdir wheelhouse
        docker cp linux_build:/tket/pytket/audited/. wheelhouse/
        docker rm --force -v linux_build
    - uses: actions/upload-artifact@v3
      with:
        name: Linux_wheels
        path: wheelhouse/
